name: QA Report (manual)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch a ejecutar'
        required: true
        default: 'main'
      tag:
        description: 'Tag/grep para las pruebas (opcional, ej: @login)'
        required: false
        default: ''

jobs:
  cypress-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Node
      # si usás nvm en el repo, ajustá la versión
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: |
          npm ci
          # Aseguramos reporter y merge tool
          npm i -D mochawesome mochawesome-merge

      - name: Run Cypress with Mochawesome
        env:
          TEST_TAG: ${{ github.event.inputs.tag }}
        run: |
          # Si usás tags/grep, agregalos acá (ajusta flags según tu proyecto)
          EXTRA_ARGS=""
          if [ -n "$TEST_TAG" ]; then
            # ejemplos posibles:
            # EXTRA_ARGS="--env grepTags=$TEST_TAG"                   # cypress-grep por tag
            # EXTRA_ARGS="--spec cypress/e2e/${TEST_TAG}.cy.js"       # si usas archivo por nombre
            echo "Ejecutando con filtro: $TEST_TAG (ajusta EXTRA_ARGS si corresponde)"
          fi

          npx cypress run \
            --reporter mochawesome \
            --reporter-options "reportFilename=mochawesome,overwrite=true,html=false,json=true,reportDir=cypress/reports" \
            $EXTRA_ARGS || true

      - name: Merge mochawesome JSONs
        run: |
          echo "Archivos generados:"
          ls -la cypress/reports || true

          if [ -f "cypress/reports/mochawesome.json" ]; then
            echo "Encontrado mochawesome.json único."
          else
            if ls cypress/reports/*.json 1> /dev/null 2>&1; then
              npx mochawesome-merge cypress/reports/*.json > cypress/reports/mochawesome.json
              echo "Merge listo -> cypress/reports/mochawesome.json"
            else
              echo "No se generaron JSONs de mochawesome (¿no hubo specs? ¿falló Cypress?)"
              exit 1
            fi
          fi

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Parse results and POST to n8n
        run: |
          RESULTS_JSON="cypress/reports/mochawesome.json"
          if [ ! -f "$RESULTS_JSON" ]; then
            echo "No existe $RESULTS_JSON"; exit 1
          fi

          PASSED=$(jq '.stats.passes // 0' "$RESULTS_JSON")
          FAILED=$(jq '.stats.failures // 0' "$RESULTS_JSON")
          DURATION=$(jq '.stats.duration // 0' "$RESULTS_JSON")

          echo "Resumen → passed=$PASSED failed=$FAILED durationMs=$DURATION"

          curl -sS -f -X POST "https://francoosunaafip.app.n8n.cloud/webhook/7851647c-e729-498e-a11a-190e03f20d81" \
            -H "Content-Type: application/json" \
            -d "{\"passed\":$PASSED,\"failed\":$FAILED,\"durationMs\":$DURATION}"

      - name: Upload mochawesome artifact (opcional)
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: cypress/reports/
