name: QA Report (manual - JSON simple y robusto)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch a ejecutar'
        required: true
        default: 'main'
      tag:
        description: 'Tag/grep para las pruebas (opcional, ej: @login)'
        required: false
        default: ''

jobs:
  cypress-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: |
          npm ci
          # Reporte JSON a archivo (no a stdout)
          npm i -D cypress-multi-reporters mocha-json-reporter
          sudo apt-get update && sudo apt-get install -y jq

      - name: Create reporter config (mocha-json → archivo)
        run: |
          mkdir -p cypress/results
          cat > reporter-config.json << 'JSON'
          {
            "reporterEnabled": "mocha-json-reporter",
            "mochaJsonReporterReporterOptions": {
              "output": "cypress/results/results.json",
              "includePending": true
            }
          }
          JSON

      - name: Run Cypress (genera cypress/results/results.json)
        env:
          TEST_TAG: ${{ github.event.inputs.tag }}
        run: |
          set -e
          EXTRA_ARGS=""
          if [ -n "$TEST_TAG" ]; then
            echo "Ejecutando con filtro: $TEST_TAG"
            # Si usas cypress-grep, descomenta:
            # EXTRA_ARGS="--env grepTags=$TEST_TAG"
            # O si querés filtrar por spec, adaptá según tu convención:
            # EXTRA_ARGS="--spec cypress/e2e/${TEST_TAG}.cy.js"
          fi

          npx cypress run \
            --reporter cypress-multi-reporters \
            --reporter-options configFile=reporter-config.json \
            $EXTRA_ARGS || true

          # Verificación mínima de que el JSON existe
          test -s cypress/results/results.json || (echo "No se generó cypress/results/results.json" && exit 1)

      - name: Mostrar stats rápidas
        run: |
          echo "Stats (si existen):"
          jq '.stats // {}' cypress/results/results.json || true

      - name: POST to n8n (JSON simple con detalles de fallos)
        env:
          WEBHOOK_URL: "https://francoosunaafip.app.n8n.cloud/webhook/7851647c-e729-498e-a11a-190e03f20d81"
        run: |
          set -euo pipefail
          RESULTS_JSON="cypress/results/results.json"

          # Totales robustos (mocha-json-reporter estructura)
          # Estructuras típicas:
          # - .stats.passes / .stats.failures / .stats.duration
          # - .tests[] con .state == "passed"/"failed" (según versión)
          PASSED=$(jq -r '.stats.passes // ([.tests[]? | select(.state=="passed" or .pass==true)] | length // 0)' "$RESULTS_JSON")
          FAILED=$(jq -r '.stats.failures // ([.tests[]? | select(.state=="failed" or .fail==true)] | length // 0)' "$RESULTS_JSON")
          DURATION=$(jq -r '.stats.duration // 0' "$RESULTS_JSON")

          # Detalle de fallos: suite + caso + archivo + error (con tolerancia de campos)
          FAILS=$(jq -c '[.tests[]?
            | select((.state=="failed") or (.fail==true))
            | {
                suite: ((.fullTitle // .title // "") | (type=="string" ? . : (.[0] // ""))),
                test:  ((.title // .fullTitle // "") | (type=="string" ? . : (.[length-1] // ""))),
                file:  (.file // .fullFile // ""),
                error: (.err.message // .err // .error // "")
              } ]' "$RESULTS_JSON")

          echo "Resumen → passed=$PASSED failed=$FAILED durationMs=$DURATION"
          echo "$FAILS" | jq -r '.[] | "- " + (.suite // "") + " :: " + (.test // "")' || true

          # Armar payload
          PAYLOAD=$(jq -n \
            --argjson passed   "$PASSED" \
            --argjson failed   "$FAILED" \
            --argjson duration "$DURATION" \
            --argjson failures "$FAILS" \
            '{passed:$passed, failed:$failed, durationMs:$duration, failures:$failures}')

          echo "POST → $WEBHOOK_URL"
          echo "$PAYLOAD" | jq .

          curl -sS -f -X POST "$WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD" \
            -w "\nHTTP_CODE=%{http_code}\n"

      - name: Upload artifacts (JSON + logs)
        uses: actions/upload-artifact@v4
        with:
          name: cypress-json-results
          path: |
            reporter-config.json
            cypress/results/results.json
