name: QA Report (manualaa)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch a ejecutar'
        required: true
        default: 'main'
      tag:
        description: 'Tag/grep para las pruebas (opcional, ej: @login)'
        required: false
        default: ''

jobs:
  cypress-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: |
          npm ci
          # Herramientas de reportes
          npm i -D mochawesome mochawesome-merge mochawesome-report-generator

      # Genera UN JSON por spec (no se pisan)
      - name: Run Cypress with Mochawesome
        env:
          TEST_TAG: ${{ github.event.inputs.tag }}
        run: |
          EXTRA_ARGS=""
          if [ -n "$TEST_TAG" ]; then
            # Ajustá según tu estrategia (cypress-grep, spec, etc.)
            # EXTRA_ARGS="--env grepTags=$TEST_TAG"
            # EXTRA_ARGS="--spec cypress/e2e/${TEST_TAG}.cy.js"
            echo "Ejecutando con filtro: $TEST_TAG (ajustá EXTRA_ARGS si corresponde)"
          fi

          npx cypress run \
            --reporter mochawesome \
            --reporter-options "overwrite=false,html=false,json=true,reportDir=cypress/reports" \
            $EXTRA_ARGS || true

      # MERGE corregido: incluye TODOS los *.json a un archivo temporal, luego renombra
      - name: Merge mochawesome JSONs (seguro)
        run: |
          set -euo pipefail
          echo "Archivos generados en cypress/reports:"
          ls -la cypress/reports || true

          # limpiar merges previos
          rm -f cypress/reports/_merged.json cypress/reports/mochawesome.json

          # entradas a mergear: base + numerados
          shopt -s nullglob
          FILES=(cypress/reports/*.json)
          shopt -u nullglob

          if [ ${#FILES[@]} -eq 0 ]; then
            echo "No se generaron JSONs de mochawesome (¿no hubo specs? ¿falló Cypress?)"
            exit 1
          fi

          echo "Entradas a mergear:"
          printf ' - %s\n' "${FILES[@]}"

          # merge a archivo temporal que NO coincida con el glob
          npx mochawesome-merge "${FILES[@]}" > cypress/reports/_merged.json

          # renombrar al estándar
          mv cypress/reports/_merged.json cypress/reports/mochawesome.json
          echo "Merge listo -> cypress/reports/mochawesome.json"

      - name: Build Mochawesome HTML
        run: |
          npx marge cypress/reports/mochawesome.json -f mochawesome -o cypress/reports
          test -f cypress/reports/mochawesome.html || (echo "No se pudo generar mochawesome.html" && exit 1)

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: "POST to n8n (multipart: resumen + html + json)"
        env:
          WEBHOOK_URL: "https://francoosunaafip.app.n8n.cloud/webhook/7851647c-e729-498e-a11a-190e03f20d81"
        run: |
          set -euo pipefail

          RESULTS_JSON="cypress/reports/mochawesome.json"
          RESULTS_HTML="cypress/reports/mochawesome.html"

          # Validaciones
          [ -f "$RESULTS_JSON" ] || { echo "No existe $RESULTS_JSON"; exit 1; }
          [ -f "$RESULTS_HTML" ] || { echo "No existe $RESULTS_HTML"; exit 1; }

          echo "Stats (según .stats del merge):"
          jq '.stats | {tests, passes, failures, pending, skipped, duration}' "$RESULTS_JSON" || true

          # ✅ Conteo REAL por estado recorriendo todo el árbol
          PASSED=$(jq '[ .. | objects | select(has("state")) | select(.state=="passed" or .state=="pass") ] | length' "$RESULTS_JSON")
          FAILED=$(jq '[ .. | objects | select(has("state")) | select(.state=="failed" or .state=="fail") ] | length' "$RESULTS_JSON")
          # Duración: usa .stats.duration si existe, si no suma por test
          DURATION=$(jq '.stats.duration // ([ .. | objects | select(has("duration")) | .duration ] | add // 0)' "$RESULTS_JSON")

          echo "Conteo real → passed=$PASSED failed=$FAILED durationMs=$DURATION"
          echo "POST → $WEBHOOK_URL"

          HTTP_CODE=$(curl -sS -X POST "$WEBHOOK_URL" \
            -H "Expect:" \
            -F "passed=$PASSED" \
            -F "failed=$FAILED" \
            -F "durationMs=$DURATION" \
            -F "report=@${RESULTS_HTML};type=text/html" \
            -F "reportJson=@${RESULTS_JSON};type=application/json" \
            -w "%{http_code}" -o /tmp/n8n_resp.txt) || true

          echo "HTTP_CODE=$HTTP_CODE"
          echo "Respuesta n8n:"
          cat /tmp/n8n_resp.txt || true
          echo

          if [ "${HTTP_CODE:0:1}" != "2" ]; then
            echo "⚠️ Multipart falló (HTTP $HTTP_CODE). Probamos envío JSON simple…"
            curl -sS -X POST "$WEBHOOK_URL" \
              -H "Content-Type: application/json" \
              -d "{\"passed\":$PASSED,\"failed\":$FAILED,\"durationMs\":$DURATION}" \
              -w "\nHTTP_CODE=%{http_code}\n" -o /tmp/n8n_resp_b.txt || true
            cat /tmp/n8n_resp_b.txt || true
            echo
          fi

      - name: Upload artifacts (opcional)
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: cypress/reports/
