name: QA Report (manual - JSON simple)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch a ejecutar'
        required: true
        default: 'main'
      tag:
        description: 'Tag/grep para las pruebas (opcional, ej: @login)'
        required: false
        default: ''

jobs:
  cypress-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: |
          npm ci

      - name: Run Cypress (reporter json → archivo)
        env:
          TEST_TAG: ${{ github.event.inputs.tag }}
        run: |
          mkdir -p cypress/results

          EXTRA_ARGS=""
          if [ -n "$TEST_TAG" ]; then
            # Ajustá según tu estrategia (cypress-grep, spec, etc.)
            # EXTRA_ARGS="--env grepTags=$TEST_TAG"
            # EXTRA_ARGS="--spec cypress/e2e/${TEST_TAG}.cy.js"
            echo "Ejecutando con filtro: $TEST_TAG (ajustá EXTRA_ARGS si corresponde)"
          fi

          # El reporter json imprime un JSON único por corrida en STDOUT → lo redirigimos a archivo
          npx cypress run --reporter json $EXTRA_ARGS > cypress/results/results.json || true

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Verificar JSON generado
        run: |
          test -s cypress/results/results.json || (echo "No se generó cypress/results/results.json" && exit 1)
          # Mostrar cabecera útil de stats (si existe)
          jq '.stats // {}' cypress/results/results.json || true

      - name: POST to n8n (JSON simple con detalles de fallos)
        env:
          WEBHOOK_URL: "https://francoosunaafip.app.n8n.cloud/webhook/7851647c-e729-498e-a11a-190e03f20d81"
        run: |
          set -euo pipefail

          RESULTS_JSON="cypress/results/results.json"

          # Totales robustos: cuenta por .tests[].state o por flags .pass/.fail si existieran
          PASSED=$(jq '[.tests[]? | select((.state=="passed") or (.state=="pass") or (.pass==true))] | length' "$RESULTS_JSON")
          FAILED=$(jq '[.tests[]? | select((.state=="failed") or (.state=="fail") or (.fail==true))] | length' "$RESULTS_JSON")

          # Duración: usa .stats.duration si existe; si no, suma duraciones de tests
          DURATION=$(jq '.stats.duration // ([.tests[]? | .duration] | add // 0)' "$RESULTS_JSON")

          # Detalle de fallos: suite + caso + archivo + error
          # - "title" del reporter json es un array: [suite, sub-suite?, test]
          #   Tomamos suite=title[0], test = último elemento (o join si preferís)
          FAILS=$(jq -c '[
            .tests[]?
            | select((.state=="failed") or (.state=="fail") or (.fail==true))
            | {
                suite: ( (.title // []) | (.[0] // "") ),
                test:  ( (.title // []) | (.[length-1] // "") ),
                file:  (.file // .fullFile // ""),
                error: (.err.message // .err // "")
              }
          ]' "$RESULTS_JSON")

          echo "Resumen → passed=$PASSED failed=$FAILED durationMs=$DURATION"
          echo "Fallos:"
          echo "$FAILS" | jq -r '.[] | "- " + (.suite // "") + " :: " + (.test // "")' || true

          # Armar payload JSON con jq para evitar problemas de escape
          PAYLOAD=$(jq -n \
            --argjson passed   "$PASSED" \
            --argjson failed   "$FAILED" \
            --argjson duration "$DURATION" \
            --argjson failures "$FAILS" \
            '{passed:$passed, failed:$failed, durationMs:$duration, failures:$failures}')

          echo "POST → $WEBHOOK_URL"
          echo "$PAYLOAD" | jq . || true

          curl -sS -f -X POST "$WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD" \
            -w "\nHTTP_CODE=%{http_code}\n"

      - name: Upload artifact (opcional)
        uses: actions/upload-artifact@v4
        with:
          name: cypress-json-results
          path: cypress/results/results.json
